#!/usr/bin/python3
#SPDX-FileCopyrightText: 2022 Uchida shou
#SPDX-License-Identifier:BSD-3-Clause
import sys

def tonum(s)
    try:
 return int(s)
 except:
                       
return int(s)
 ans = 0
 for line in sys.stdin:
    line = line.rstrip()
    ans += tonums(line)
 print(ans)
                             

                                



