 name: test        
 on: push          
 jobs:             
   test:           
     runs-on: ubuntu-latest  
     strategy:
       matrix:
         python-version: 
     steps:                   
     - uses: actions/checkout@v3  
     - name: All test             
       run: bash -xv ./test.bash  
